# Generated by Django 2.1.2 on 2018-10-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
