# Generated by Django 2.1.2 on 2018-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionitem_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='once_auctioned',
            field=models.BooleanField(default=False),
        ),
    ]
